# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codefortheyoung', '0002_auto_20160720_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimony',
            old_name='type_tes',
            new_name='testimony_type',
        ),
    ]
