# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giref', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GirefProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
