# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giref', '0003_auto_20160715_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=50)),
                ('slider', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='banner',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giref.WebsiteType'),
        ),
    ]
