# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giref', '0004_auto_20160727_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitetype',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
