# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giref', '0005_auto_20160727_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='slider',
            field=models.BooleanField(default=False, verbose_name='Is the Image part of a set of slider?'),
        ),
    ]
