# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giref', '0009_auto_20160727_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='')),
                ('slider', models.BooleanField(default=False, verbose_name='Is the Image part of a set of slider?')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giref.WebsiteType')),
            ],
        ),
    ]
