# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giref', '0012_auto_20160727_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='caption',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
